# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20170612_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='creator_id',
            field=models.IntegerField(default=1),
        ),
    ]
